apiVersion: batch/v1
kind: CronJob
metadata:
  name: simple-node-job
  namespace: ckad-job
spec:
  schedule: "30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: checker
            image: node
            command: ["ps", "-eaf"]
          restartPolicy: OnFailure
# https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
