apiVersion: v1
kind: Pod
metadata:
  name: volume-share-xfusion
spec:
  containers:
    - name: volume-container-xfusion-1
      image: ubuntu:latest
      command: ["sleep", "99999"]
      volumeMounts:
        - name: volume-share
          mountPath: /tmp/official
    - name: volume-container-xfusion-2
      image: ubuntu:latest
      command: ["sleep", "99999"]
      volumeMounts:
        - name: volume-share
          mountPath: /tmp/apps   
  volumes:
    - name: volume-share
      emptyDir:
        sizeLimit: 500Mi
